Auditing randomly selected lowest professors within Humanities department bucket:

- Paula Levine
- Jennifer Rycenga
- James Matray
- Julie Paulson
- Swathi Vanniarajan

In [2]:
import pandas as pd

csu_data_df = pd.read_parquet('../Data/model_csu_depbucket_cleaned_joined_pay_2013-2024.parquet')
csu_data_df.head(5)

,year_transparentCA,school,name,title,job,original_department,department,total_pay,base_pay,overtime_pay,other_pay
0,2013,CSU Bakersfield,Abbas Grammy,Professor Emeritus,instructional faculty - academic year,Economics,"Business, Economics & Finance",148840,97454,0,51386
1,2014,CSU Bakersfield,Abbas Grammy,Professor Emeritus,instructional faculty - academic year,Economics,"Business, Economics & Finance",164953,98207,0,66746
2,2015,CSU Bakersfield,Abbas Grammy,Professor Emeritus,instructional faculty - academic year,Economics,"Business, Economics & Finance",155361,100861,0,54500
3,2016,CSU Bakersfield,Abbas Grammy,Professor Emeritus,instructional faculty - academic year,Economics,"Business, Economics & Finance",146317,102539,0,43778
4,2017,CSU Bakersfield,Abbas Grammy,Professor Emeritus,instructional faculty - academic year,Economics,"Business, Economics & Finance",134508,99024,0,35484

It looks like Paula's pay is normal for every year but 2024, so potentially she retired or took 2024 off.

In [4]:
paula = csu_data_df[csu_data_df["name"] == "Paula Levine"]
paula

,year_transparentCA,school,name,title,job,original_department,department,total_pay,base_pay,overtime_pay,other_pay
93417,2013,San Francisco State University,Paula Levine,Professor,instructional faculty - academic year,Art,Humanities & Languages,88358,88358,0,0
93418,2014,San Francisco State University,Paula Levine,Professor,instructional faculty - academic year,Art,Humanities & Languages,89735,89735,0,0
93419,2015,San Francisco State University,Paula Levine,Professor,instructional faculty - academic year,Art,Humanities & Languages,91174,91174,0,0
93420,2016,San Francisco State University,Paula Levine,Professor,instructional faculty - academic year,Art,Humanities & Languages,67610,67610,0,0
93421,2017,San Francisco State University,Paula Levine,Professor,instructional faculty - academic year,Art,Humanities & Languages,97967,97767,0,200
93422,2018,San Francisco State University,Paula Levine,Professor,instructional faculty - academic year,Art,Humanities & Languages,99711,99711,0,0
93423,2019,San Francisco State University,Paula Levine,Professor,instructional faculty - academic year,Art,Humanities & Languages,104074,104074,0,0
93424,2020,San Francisco State University,Paula Levine,Professor,instructional faculty - academic year,Art,Humanities & Languages,108150,107400,0,750
93425,2021,San Francisco State University,Paula Levine,Professor,instructional faculty - academic year,Art,Humanities & Languages,92503,92863,0,-360
93426,2022,San Francisco State University,Paula Levine,Professor,instructional faculty - academic year,Art,Humanities & Languages,103676,95255,0,8420
93427,2023,San Francisco State University,Paula Levine,Professor,instructional faculty - academic year,Art,Humanities & Languages,86395,76795,0,9599
93428,2024,San Francisco State University,Paula Levine,Professor,instructional faculty - academic year,Art,Humanities & Languages,984,492,0,492

Jennifer is the same as Paula

In [5]:
jennifer = csu_data_df[csu_data_df["name"] == "Jennifer Rycenga"]
jennifer

,year_transparentCA,school,name,title,job,original_department,department,total_pay,base_pay,overtime_pay,other_pay
96907,2013,San Jose State University,Jennifer Rycenga,Professor,instructional faculty - academic year,Humanities,Humanities & Languages,100114,93331,0,6783
96908,2014,San Jose State University,Jennifer Rycenga,Professor,instructional faculty - academic year,Humanities,Humanities & Languages,89090,82157,0,6933
96909,2015,San Jose State University,Jennifer Rycenga,Professor,instructional faculty - academic year,Humanities,Humanities & Languages,63888,63888,0,0
96910,2016,San Jose State University,Jennifer Rycenga,Professor,instructional faculty - academic year,Humanities,Humanities & Languages,100034,100034,0,0
96911,2017,San Jose State University,Jennifer Rycenga,Professor,instructional faculty - academic year,Humanities,Humanities & Languages,106085,106085,0,0
96912,2018,San Jose State University,Jennifer Rycenga,Professor,instructional faculty - academic year,Humanities,Humanities & Languages,107685,107685,0,0
96913,2019,San Jose State University,Jennifer Rycenga,Professor,instructional faculty - academic year,Humanities,Humanities & Languages,112605,112605,0,0
96914,2020,San Jose State University,Jennifer Rycenga,Professor,instructional faculty - academic year,Humanities,Humanities & Languages,115442,114567,0,875
96915,2022,San Jose State University,Jennifer Rycenga,Professor,instructional faculty - academic year,Humanities,Humanities & Languages,120316,112729,0,7587
96916,2023,San Jose State University,Jennifer Rycenga,Professor,instructional faculty - academic year,Humanities,Humanities & Languages,94516,83918,0,10597
96917,2024,San Jose State University,Jennifer Rycenga,Professor,instructional faculty - academic year,Humanities,Humanities & Languages,526,526,0,0

James is just paid a lot less starting in 2020. Should investigate

In [6]:
james = csu_data_df[csu_data_df["name"] == "James Matray"]
james

,year_transparentCA,school,name,title,job,original_department,department,total_pay,base_pay,overtime_pay,other_pay
47440,2013,"California State University, Chico",James Matray,Emeritus,instructional faculty - academic year,History,Humanities & Languages,94920,94738,0,182
47441,2014,"California State University, Chico",James Matray,Emeritus,instructional faculty - academic year,History,Humanities & Languages,96564,96291,0,273
47442,2015,"California State University, Chico",James Matray,Emeritus,instructional faculty - academic year,History,Humanities & Languages,98676,98494,0,182
47443,2016,"California State University, Chico",James Matray,Emeritus,instructional faculty - academic year,History,Humanities & Languages,100385,100112,0,273
47444,2017,"California State University, Chico",James Matray,Emeritus,instructional faculty - academic year,History,Humanities & Languages,105363,105181,0,182
47445,2018,"California State University, Chico",James Matray,Emeritus,instructional faculty - academic year,History,Humanities & Languages,108568,108386,0,182
47446,2019,"California State University, Chico",James Matray,Emeritus,instructional faculty - academic year,History,Humanities & Languages,98285,88787,0,9498
47447,2020,"California State University, Chico",James Matray,Emeritus,instructional faculty - academic year,History,Humanities & Languages,57780,57780,0,0
47448,2021,"California State University, Chico",James Matray,Emeritus,instructional faculty - academic year,History,Humanities & Languages,57780,57780,0,0
47449,2022,"California State University, Chico",James Matray,Emeritus,instructional faculty - academic year,History,Humanities & Languages,61802,61802,0,0
47450,2023,"California State University, Chico",James Matray,Emeritus,instructional faculty - academic year,History,Humanities & Languages,61890,61890,0,0
47451,2024,"California State University, Chico",James Matray,Emeritus,instructional faculty - academic year,History,Humanities & Languages,50029,50029,0,0

Julie is just paid significantly less in 2024 than previous years

In [7]:
julie = csu_data_df[csu_data_df["name"] == "Julie Paulson"]
julie

,year_transparentCA,school,name,title,job,original_department,department,total_pay,base_pay,overtime_pay,other_pay
92067,2013,San Francisco State University,Julie Paulson,Professor,instructional faculty - academic year,English Language and Literature,Humanities & Languages,78515,71162,0,7353
92068,2014,San Francisco State University,Julie Paulson,Professor,instructional faculty - academic year,English Language and Literature,Humanities & Languages,80837,73331,0,7506
92069,2015,San Francisco State University,Julie Paulson,Professor,instructional faculty - academic year,English Language and Literature,Humanities & Languages,88426,87425,0,1000
92070,2016,San Francisco State University,Julie Paulson,Professor,instructional faculty - academic year,English Language and Literature,Humanities & Languages,78062,78062,0,0
92071,2017,San Francisco State University,Julie Paulson,Professor,instructional faculty - academic year,English Language and Literature,Humanities & Languages,91085,81180,0,9905
92072,2018,San Francisco State University,Julie Paulson,Professor,instructional faculty - academic year,English Language and Literature,Humanities & Languages,100288,90855,0,9433
92073,2019,San Francisco State University,Julie Paulson,Professor,instructional faculty - academic year,English Language and Literature,Humanities & Languages,107616,107416,0,200
92074,2020,San Francisco State University,Julie Paulson,Professor,instructional faculty - academic year,English Language and Literature,Humanities & Languages,110714,108964,0,1750
92075,2021,San Francisco State University,Julie Paulson,Professor,instructional faculty - academic year,English Language and Literature,Humanities & Languages,109917,108917,0,1000
92076,2022,San Francisco State University,Julie Paulson,Professor,instructional faculty - academic year,English Language and Literature,Humanities & Languages,121178,115928,0,5250
92077,2023,San Francisco State University,Julie Paulson,Professor,instructional faculty - academic year,English Language and Literature,Humanities & Languages,89592,89542,0,50
92078,2024,San Francisco State University,Julie Paulson,Professor,instructional faculty - academic year,English Language and Literature,Humanities & Languages,33715,33715,0,0

Swathi just not paid alot

In [8]:
swathi = csu_data_df[csu_data_df["name"] == "Swathi Vanniarajan"]
swathi

,year_transparentCA,school,name,title,job,original_department,department,total_pay,base_pay,overtime_pay,other_pay
100041,2021,San Jose State University,Swathi Vanniarajan,Chair,instructional faculty - academic year,Linguistics & Language Development,Humanities & Languages,55890,54390,0,1500
100042,2022,San Jose State University,Swathi Vanniarajan,Chair,instructional faculty - academic year,Linguistics & Language Development,Humanities & Languages,58683,58183,0,500
100043,2023,San Jose State University,Swathi Vanniarajan,Chair,instructional faculty - academic year,Linguistics & Language Development,Humanities & Languages,58266,58266,0,0
100044,2024,San Jose State University,Swathi Vanniarajan,Chair,instructional faculty - academic year,Linguistics & Language Development,Humanities & Languages,47611,47611,0,0