In [ ]:
%pip install ./requirements.txt

Note: you may need to restart the kernel to use updated packages.

ERROR: Invalid requirement: './requirements.txt': Expected package name at the start of dependency specifier
    ./requirements.txt
    ^

In [10]:
import pandas as pd
import duckdb
import numpy as np

conn = duckdb.connect()

In [5]:
# Read the entire parquet file
df = pd.read_parquet("./Data/faculty-salaries.parquet")

In [7]:
df.head()

,name,job,department,base,overtime,other,ual,benefitsee,benefitser,benefitsdc,notes,totalpay,totalbenefits,totalpaybenefits,year
0,No records found.,NaN,Allan Hancock College,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011
1,Miller Elizabeth,Assoc Supt/VP Admin Services,NaN,144823.00,0.0,47936.01,NaN,NaN,NaN,NaN,NaN,192759.01,24418.92,217177.93,2012
2,Bierly Gary,FT Faculty,NaN,96461.44,0.0,51841.35,NaN,NaN,NaN,NaN,NaN,148302.79,24710.55,173013.34,2012
3,Comstock Marie,FT Faculty,NaN,96461.04,0.0,45063.48,NaN,NaN,NaN,NaN,NaN,141524.52,21697.77,163222.29,2012
4,Sanchez Luis,Assoc Supt/VP Academic Affairs,NaN,135267.00,0.0,0.00,NaN,NaN,NaN,NaN,NaN,135267.00,23170.20,158437.20,2012

No rows with ual, benefitsee, benefitser, benefitsdc

In [16]:
df.count()

name                5345243
job                 5345131
department              137
base                5345131
overtime            5345131
other               5345131
ual                       0
benefitsee                0
benefitser                0
benefitsdc                0
notes                 28494
totalpay            5345115
totalbenefits       5345131
totalpaybenefits    5345128
year                5345243
dtype: int64

Some values have a total pay that is negative. Why is this? Should they just be removed?

In [19]:
pay_less_than_0 = df[df['totalpay'] < 0]
pay_less_than_0.head()

,name,job,department,base,overtime,other,ual,benefitsee,benefitser,benefitsdc,notes,totalpay,totalbenefits,totalpaybenefits,year
2821,DAVID S HARMER,CARPENTER,NaN,-221.14,49.12,9.00,NaN,NaN,NaN,NaN,NaN,-163.02,0.0,-163.02,2011
3053,JOHN R SANDHAGEN,"EQUIPMENT TECHNICIAN I, SPECIALIZED EQUIPMENT",NaN,0.00,0.00,-153.79,NaN,NaN,NaN,NaN,NaN,-153.79,0.0,-153.79,2011
5525,JAMIE L CORLEY,ADMINISTRATIVE SUPPORT ASSISTANT -12 MONTH,NaN,-1991.79,0.00,0.00,NaN,NaN,NaN,NaN,NaN,-1991.79,0.0,-1991.79,2011
7789,THOMAS E HAWKINS,LECTURER - ACADEMIC YEAR,NaN,-114.45,0.00,0.00,NaN,NaN,NaN,NaN,NaN,-114.45,0.0,-114.45,2011
8408,ANDREA L BRAUNINGER,PHYSICIAN,NaN,-221.65,0.00,0.00,NaN,NaN,NaN,NaN,NaN,-221.65,0.0,-221.65,2011

In [20]:
rows_with_notes = df.dropna(subset=['notes'])
rows_with_notes.head()

,name,job,department,base,overtime,other,ual,benefitsee,benefitser,benefitsdc,notes,totalpay,totalbenefits,totalpaybenefits,year
150536,Leobigildo Cota Jr,Administrator I,NaN,9530.91,0.0,8.00,NaN,NaN,NaN,NaN,Employee holds multiple positions.,9538.91,3344.00,12882.91,2013
150590,Kathy A Fernandes,Administrator II,NaN,122687.68,0.0,35397.83,NaN,NaN,NaN,NaN,Employee holds multiple positions.,158085.51,47011.89,205097.40,2013
150591,Kathleen L Flachmeier,Administrator II,NaN,6276.18,0.0,27067.14,NaN,NaN,NaN,NaN,Employee holds multiple positions.,33343.32,2300.49,35643.81,2013
150636,Sabrina K Sanders,Administrator II,NaN,69412.61,0.0,60.00,NaN,NaN,NaN,NaN,Employee holds multiple positions.,69472.61,22435.71,91908.32,2013
150703,Robin D Innes,Administrator III,NaN,95384.96,0.0,1008.00,NaN,NaN,NaN,NaN,Employee holds multiple positions.,96392.96,27698.42,124091.38,2013

In [15]:
#clean dataset, remove rows missing name or totalpay
#after count rows missing job and department, but keep them in the dataset
clean_df = df.dropna(subset=['name', 'totalpay'])
#remove total pay under baseline salary (start 10,000)
clean_df = clean_df[clean_df['totalpay'] >= 10000]
clean_df.count()

name                3544483
job                 3544483
department               25
base                3544483
overtime            3544483
other               3544483
ual                       0
benefitsee                0
benefitser                0
benefitsdc                0
notes                 26018
totalpay            3544483
totalbenefits       3544483
totalpaybenefits    3544483
year                3544483
dtype: int64

In [14]:
col = df["totalpay"]

col.mean()                                         # center — sensitive
col.median()                                       # center — robust
col.std()    
col.min()
col.max()                                        # spread — sensitive
print("Mean:", col.mean())
print("Median:", col.median())
print("Standard Deviation:", col.std())
print("Minimum:", col.min())
print("Maximum:", col.max())
print("IQR:", col.quantile(0.75) - col.quantile(0.25))

Mean: 52426.11727489119
Median: 32719.0
Standard Deviation: 71412.07444136753
Minimum: -331742.0
Maximum: 7061667.0
IQR: 68102.015

TypeError: Index(...) must be called with a collection of some kind, True was passed